spring:
  profiles:
    active: prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: ozxr nebh fehr pvhb  # App password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
   
   
   
   
  